## < ASLAM AUTOGENERATED CODE; DO NOT MODIFY > ##

adde = lambda a, b: {'adde': [a, b]}

sube = lambda a, b: {'sube': [a, b]}

mule = lambda a, b: {'mule': [a, b]}

dive = lambda a, b: {'dive': [a, b]}

mode = lambda a, b: {'mode': [a, b]}

powe = lambda a, b: {'powe': [a, b]}

nege = lambda a: {'nege': a}

gte = lambda a, b: {'gte': [a, b]}

gee = lambda a, b: {'gee': [a, b]}

eqe = lambda a, b: {'eqe': [a, b]}

lee = lambda a, b: {'lee': [a, b]}

lte = lambda a, b: {'lte': [a, b]}

sine = lambda a: {'sine': a}

cose = lambda a: {'cose': a}

tane = lambda a: {'tane': a}

atan2e = lambda a, b: {'atan2e': [a, b]}

vece = lambda a: {'vece': a}

inde = lambda a, b: {'inde': [a, b]}

casee = lambda a: {'casee': a}

lete = lambda a, b, c: {'lete': [a, b, c]}

vare = lambda a: {'vare': a}

lite = lambda a: {'lite': a}