## < ASLAM AUTOGENERATED CODE; DO NOT MODIFY > ##

boolt = lambda : {'boolt': []}

boundedrealt = lambda a, b: {'boundedrealt': {'min': a, 'max': b}}

finitesett = lambda a: {'finitesett': {'options': a}}

vectort = lambda a: {'vectort': a}