## < ASLAM AUTOGENERATED CODE; DO NOT MODIFY > ##

add = lambda a, b: {'add': [a, b]}

sub = lambda a, b: {'sub': [a, b]}

mul = lambda a, b: {'mul': [a, b]}

div = lambda a, b: {'div': [a, b]}

mod = lambda a, b: {'mod': [a, b]}

pow = lambda a, b: {'pow': [a, b]}

neg = lambda a: {'neg': a}

sin = lambda a: {'sin': a}

cos = lambda a: {'cos': a}

tan = lambda a: {'tan': a}

vec = lambda a: {'vec': a}

ind = lambda a, b: {'ind': [a, b]}

doublel = lambda a: {'doublel': a}

case = lambda a: {'case': a}

let = lambda a, b, c: {'let': [a, b, c]}

var = lambda a: {'var': a}