## < ASLAM AUTOGENERATED CODE; DO NOT MODIFY > ##

boundedreal = lambda a, b: {'boundedreal': {'min': a, 'max': b}}

finiteset = lambda a: {'finiteset': {'options': a}}

vector = lambda a: {'vector': a}