import time
import shm
import shm.recovery_results as r
import os

# might be cool to simulate the pinger

#print("zero shm variables")
#r.pinger_heading.set(0)
#r.doubloon_1_probability.set(0)
#os.system("auv-shm reset --HARD")


print("in TrackPinger")
shm.camera.downward_height.set(1020)
shm.camera.downward_width.set(1020)
shm.camera.downward_height.set(1020)
shm.camera.downward_width.set(1020)
r.tower_forward_area.set(0)
r.tower_downward_area.set(0)
r.doubloon_1_probability.set(0)
r.doubloon_2_probability.set(0)
r.pinger_confidence.set(0)
r.table_area.set(0)
r.first_mark_score.set(0)
r.pinger_heading.set(80)
time.sleep(10)
print("changing pinger heading")
r.pinger_heading.set(120)
time.sleep(10)
print("after following the pinger for a while, we find the tower in the forward camera")
r.tower_forward_area.set(99999999)
r.tower_downward_area.set(0)
print("now we should be in ForwardAlignTower")
r.tower_forward_center_x.set(300)
r.tower_forward_center_y.set(300)
time.sleep(5)
print("after forwardaligning for a while, we find the tower in the downward camera")
r.tower_forward_center_x.set(shm.camera.forward_width.get() / 2)
r.tower_forward_center_y.set(shm.camera.forward_height.get() / 2)
r.tower_downward_area.set(99999999)
r.doubloon_1_probability.set(0)
r.doubloon_2_probability.set(0)

print("now we should be in GrabDoubloon")
print("GrabDoubloon's FindDoubloon task should be spiraling the sub now")
time.sleep(12)
print("after spiraling for a while, we find a doubloon")
print("setting doubloon prob to 1...")
r.doubloon_1_probability.set(1.0)
r.doubloon_1_x.set(300)
r.doubloon_1_y.set(300)
print("aligning with doubloon")
time.sleep(5)
r.doubloon_1_x.set(shm.camera.downward_width.get() / 2)
r.doubloon_1_y.set(shm.camera.downward_height.get() / 2)
print("now we should be be diving for the doubloon")
time.sleep(5)
r.doubloon_1_probability.set(0.0)
print("should be surfacing now, grabbing succeeded")
r.tower_downward_center_x.set(300)
r.tower_downward_center_y.set(300)
time.sleep(5)
r.tower_downward_center_x.set(shm.camera.downward_width.get() / 2)
r.tower_downward_center_y.set(shm.camera.downward_height.get() / 2)
# Prepare DownwardAlignTable
r.table_center_x.set(300)
r.table_center_y.set(300)
r.first_mark_x.set(300)
r.first_mark_y.set(300)
r.first_mark_score.set(10000)
r.second_mark_score.set(0)
time.sleep(15)

print("done surfacing, should be in downwardaligntable now")
time.sleep(5)
r.first_mark_x.set(shm.camera.downward_width.get() / 2)
r.first_mark_y.set(shm.camera.downward_height.get() / 2)
print("targeting first marker")
time.sleep(5)
print("centered on first mark")
r.first_mark_x.set(shm.camera.downward_width.get() / 2)
r.first_mark_y.set(shm.camera.downward_height.get() / 2)

print("now we should be in dropdoubloon")
r.doubloon_1_probability.set(1.0)
r.doubloon_1_x.set(shm.camera.downward_width.get() / 2)
r.doubloon_1_y.set(shm.camera.downward_height.get() / 2)
print("finished!")
