flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.3.1.1
- MonadCatchIO-transformers-0.3.1.3
- SHA-1.6.4.2
- aeson-0.11.0.0
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- attoparsec-0.13.0.1
- attoparsec-enumerator-0.3.4
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.1
- blaze-builder-enumerator-0.2.1.0
- byteable-0.1.1
- bytestring-builder-0.10.6.0.0
- bytestring-mmap-0.2.2
- case-insensitive-1.2.0.5
- cryptohash-0.11.6
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- dlist-0.7.1.2
- double-conversion-2.0.1.0
- entropy-0.3.7
- enumerator-0.4.20
- extensible-exceptions-0.1.1.4
- fail-4.9.0.0
- hashable-1.2.4.0
- lzma-0.0.0.1
- monads-tf-0.1.0.2
- mtl-2.2.1
- mwc-random-0.13.3.2
- nanomsg-haskell-0.2.3
- network-2.6.2.1
- network-info-0.2.0.8
- normaldistribution-1.1.0.3
- old-locale-1.0.0.7
- optparse-applicative-0.12.1.0
- primitive-0.6.1.0
- pseudomacros-0.0.2
- random-1.1
- regex-base-0.93.2
- regex-posix-0.95.2
- safe-0.3.9
- scientific-0.3.4.4
- semigroups-0.18.1
- snap-core-0.9.8.0
- snap-server-0.9.5.1
- stm-2.4.4.1
- streaming-commons-0.1.15.1
- syb-0.6
- tagged-0.8.3
- text-1.2.2.0
- transformers-compat-0.5.1.4
- unix-compat-0.4.1.4
- unordered-containers-0.2.6.0
- uuid-1.3.11
- uuid-types-1.0.2
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- websockets-0.9.6.1
- websockets-snap-0.9.2.0
- zlib-0.6.1.1
- zlib-bindings-0.1.1.5
- zlib-enum-0.2.3.1
resolver: ghc-7.10.3
