## < ASLAM AUTOGENERATED CODE; DO NOT MODIFY > ##

adde = lambda a, b: {'adde': [a, b]}

sube = lambda a, b: {'sube': [a, b]}

mule = lambda a, b: {'mule': [a, b]}

dive = lambda a, b: {'dive': [a, b]}

mode = lambda a, b: {'mode': [a, b]}

sine = lambda a: {'sine': a}

cose = lambda a: {'cose': a}

tane = lambda a: {'tane': a}

gaussiane = lambda a, b, c: {'gaussiane': [a, b, c]}

dote = lambda a, b: {'dote': [a, b]}

norme = lambda a: {'norme': a}

inde = lambda a, b: {'inde': [a, b]}

vece = lambda a: {'vece': a}

lite = lambda a: {'lite': a}

vare = lambda a: {'vare': a}

appe = lambda a, b: {'appe': [a, b]}