[devices.brendhim.vars]
PitchOffset = "him_settings.pitchoffset"
RollOffset = "him_settings.rolloffset"
XCompOffset = "him_settings.xcompoffset"
YAccelOffset = "him_settings.yacceloffset"
ZAccelOffset = "him_settings.zacceloffset"
HeadingOffset = "him_settings.heading_offset"
XAccelOffset = "him_settings.xacceloffset"
ZCompOffset = "him_settings.zcompoffset"
YCompOffset = "him_settings.ycompoffset"

RollVel = "him.roll_vel"
Pitch = "him.pitch"
YAccel = "him.y_accel"
MagY = "him.mag_y"
Roll = "him.roll"
XAccel = "him.x_accel"
MagZ = "him.mag_z"
PitchVel = "him.pitch_vel"
YawVel = "him.yaw_vel"
Heading = "him.heading"
MagX = "him.mag_x"
ZAccel = "him.z_accel"
