[devices.him.vars]
AccelX = "him.x_accel"
AccelY = "him.y_accel"
AccelZ = "him.z_accel"
RollVel = "him.roll_vel"
PitchVel = "him.pitch_vel"
YawVel = "him.yaw_vel"
MagX = "him.mag_x"
MagY = "him.mag_y"
MagZ = "him.mag_z"
Heading = "him.heading"
Pitch = "him.pitch"
Roll = "him.roll"
Temp = "him.gyro_temp"
