[devices.minipower.vars]
Voltage5VDCDC = "minipower_status.voltage_5v"
Current5VDCDC = "minipower_status.current_5v"
Voltage12VDCDC = "minipower_status.voltage_12v"
Current12VDCDC = "minipower_status.current_12v"
Current5V1 = "minipower_status.current_5v_him"
Current5V2 = "minipower_status.current_5v_depth"
Current5V3 = "minipower_status.current_5v_sensu"
Current5V4 = "minipower_status.current_5v_serial"
Current12V1 = "minipower_status.current_12v_x1"
Current12V2 = "minipower_status.current_12v_gx1"
Current12V3 = "minipower_status.current_12v_actuators"
Current12V4 = "minipower_status.current_12v_altimeter"
Current12V5 = "minipower_status.current_12v_computer"
Current = "minipower_status.current"
Vout = "minipower_status.vout"
Enable5V1 = "minipower.enable_5v_him"
Enable5V2 = "minipower.enable_5v_depth"
Enable5V3 = "minipower.enable_5v_sensu"
Enable12V1 = "minipower.enable_12v_x1"
Enable12V2 = "minipower.enable_12v_gx1"
Enable12V3 = "minipower.enable_12v_actuators"
Enable12V4 = "minipower.enable_12v_altimeter"
