[devices.sensuator.vars]
Act1Trigger = "actuator_desires.trigger_01"
Act2Trigger = "actuator_desires.trigger_02"
Act3Trigger = "actuator_desires.trigger_03"
Act4Trigger = "actuator_desires.trigger_04"
Act5Trigger = "actuator_desires.trigger_05"
Act6Trigger = "actuator_desires.trigger_06"
DepthPresent = "depth.present"
DepthOffset = "depth.offset"
Depth = "depth.depth"
Pressure = "pressure.hull"
HullTemp = "temperature.hull"
WaterTemp = "temperature.water"
WaterPressure = "pressure.water"
