[devices.thruster.vars]
ForeStarboard = "motor_desires.fore_starboard"
AftStarboard = "motor_desires.aft_starboard"
SurgeStarboard = "motor_desires.starboard"
ForePort = "motor_desires.fore_port"
AftPort = "motor_desires.aft_port"
SurgePort = "motor_desires.port"
SwayFore = "motor_desires.sway_fore"
SwayAft = "motor_desires.sway_aft"
RampDec = "ramp.ramp_dec"
RampInc = "ramp.ramp_inc"
RampPeriod = "ramp.ramp_period"
ForeStarboardRamp = "ramp_status.fore_starboard_ramp"
AftStarboardRamp = "ramp_status.aft_starboard_ramp"
SurgeStarboardRamp = "ramp_status.starboard_ramp"
ForePortRamp = "ramp_status.fore_port_ramp"
AftPortRamp = "ramp_status.aft_port_ramp"
SurgePortRamp = "ramp_status.port_ramp"
SwayForeRamp = "ramp_status.sway_fore_ramp"
SwayAftRamp = "ramp_status.sway_aft_ramp"
