# TODO get wall-tower headings for Transdec regions
# PINGER_FREQUENCY = 30000 # Region A
# PINGER_FREQUENCY = 40000 # Region B
# PINGER_FREQUENCY = 25000 # Region C
# PINGER_FREQUENCY = 35000 # Region D

PINGER_FREQUENCY = 30000
TRACK_MAG_THRESH = 10.8
TRACK_COOLDOWN_SAMPLES = 188000

RIGHT_HANDED = False

PATH_1_BEND_RIGHT = RIGHT_HANDED
PATH_2_BEND_RIGHT = RIGHT_HANDED
