[devices.actuator.vars]
Motor1 = "actuator_desires.motor_pwm_1"
Motor2 = "actuator_desires.motor_pwm_2"
Motor1Current = "actuator_status.motor_current_1"
Motor2Current = "actuator_status.motor_current_2"
FuseStatus = "actuator_status.blown_fuses"
Act1Trigger = "actuator_desires.trigger_01"
Act2Trigger = "actuator_desires.trigger_02"
Act3Trigger = "actuator_desires.trigger_03"
Act4Trigger = "actuator_desires.trigger_04"
Act5Trigger = "actuator_desires.trigger_05"
Act6Trigger = "actuator_desires.trigger_06"
Act7Trigger = "actuator_desires.trigger_07"
Act8Trigger = "actuator_desires.trigger_08"
Act9Trigger = "actuator_desires.trigger_09"
Act10Trigger = "actuator_desires.trigger_10"
Act11Trigger = "actuator_desires.trigger_11"
Act12Trigger = "actuator_desires.trigger_12"
Act13Trigger = "actuator_desires.trigger_13"
Act14Trigger = "actuator_desires.trigger_14"
