[devices.thrusters_mini.vars]
Thruster1PwmVal = "motor_desires.port"
Thruster2PwmVal = "motor_desires.fore_port"
Thruster3PwmVal = "motor_desires.aft_port"
Thruster4PwmVal = "motor_desires.sway_aft"
Thruster5PwmVal = "motor_desires.aft_starboard"
Thruster6PwmVal = "motor_desires.fore_starboard"
Thruster7PwmVal = "motor_desires.starboard"
Thruster8PwmVal = "motor_desires.sway_fore"

Thruster1PwmReadback = "ramp_status.port_ramp"
Thruster2PwmReadback = "ramp_status.fore_port_ramp"
Thruster3PwmReadback = "ramp_status.sway_fore_ramp"
Thruster4PwmReadback = "ramp_status.aft_port_ramp"
Thruster5PwmReadback = "ramp_status.sway_aft_ramp"
Thruster6PwmReadback = "ramp_status.fore_starboard_ramp"
Thruster7PwmReadback = "ramp_status.aft_starboard_ramp"
Thruster8PwmReadback = "ramp_status.starboard_ramp"

RampPeriod = "ramp.ramp_period"
RampInc = "ramp.ramp_inc"
RampDec = "ramp.ramp_dec"
