[devices.thrusters.vars]
Thruster1PwmVal = "motor_desires.port"
Thruster2PwmVal = "motor_desires.sway_fore"
Thruster3PwmVal = "motor_desires.aft_starboard"
Thruster4PwmVal = "motor_desires.sway_aft"
Thruster5PwmVal = "motor_desires.starboard"
Thruster6PwmVal = "motor_desires.fore_port"

RampPeriod = "ramp.ramp_period"
RampInc = "ramp.ramp_inc"
RampDec = "ramp.ramp_dec"
