[devices.HIM.vars]
acc_x = "him.x_accel"
acc_y = "him.y_accel"
acc_z = "him.z_accel"
gyr_x = "him.roll_vel"
gyr_y = "him.pitch_vel"
gyr_z = "him.yaw_vel"
mag_x = "him.mag_x"
mag_y = "him.mag_y"
mag_z = "him.mag_z"
heading = "him.heading"
pitch = "him.pitch"
roll = "him.roll"
#Temp = "him.gyro_temp"

