[devices.thruster_board_2.vars]
Thruster1PwmVal = "motor_desires.aft_port"
Thruster2PwmVal = "motor_desires.port"
Thruster3PwmVal = "motor_desires.sway_fore"
Thruster4PwmVal = "motor_desires.fore_port"

Thruster1PwmReadback = "ramp_status.aft_port_ramp"
Thruster2PwmReadback = "ramp_status.port_ramp"
Thruster3PwmReadback = "ramp_status.sway_fore_ramp"
Thruster4PwmReadback = "ramp_status.fore_port_ramp"

RampPeriod = "ramp.ramp_period"
RampInc = "ramp.ramp_inc"
RampDec = "ramp.ramp_dec"

