[devices.thrusters.vars]
Thruster1PwmVal = "motor_desires.fore_starboard"
Thruster2PwmVal = "motor_desires.starboard"
Thruster3PwmVal = "motor_desires.sway_aft"
Thruster4PwmVal = "motor_desires.aft_starboard"

Thruster1PwmReadback = "ramp_status.fore_starboard_ramp"
Thruster2PwmReadback = "ramp_status.starboard_ramp"
Thruster3PwmReadback = "ramp_status.sway_aft_ramp"
Thruster4PwmReadback = "ramp_status.aft_starboard_ramp"

RampPeriod = "ramp.ramp_period"
RampInc = "ramp.ramp_inc"
RampDec = "ramp.ramp_dec"

