[devices.merge.vars]
VehicleCurrent = "merge_status.total_current"
VehicleVoltage = "merge_status.total_voltage"
MissionLED = "merge.mission_led"
MissionStart = "merge_status.mission_start"
# SubRestart = "merge_status.sub_restart"

[devices.merge.options]
canHardKill = true
