[devices.merge.vars]
Vout = "merge_status.total_voltage"
overrideKill = "merge.override_kill"
restart = "merge.arm_for_restart"
useInternADC = "merge.use_internal_adc"
isRestarting = "merge_status.is_restarting"
reading = "merge_status.raw_adc"
isKilled = "switches.hard_kill"
