[devices.minithruster.vars]
#DepthFore = "motor_desires.fore_port"
#DepthAft = "motor_desires.aft_starboard"
#SwayPort = "motor_desires.sway_aft"
#SwayStarboard = "motor_desires.sway_fore"
#SurgePort = "motor_desires.port"
#SurgeStarboard = "motor_desires.starboard"

DepthFore = "motor_desires.sway_aft"
DepthAft = "motor_desires.port"
SwayPort = "motor_desires.fore_port"
SwayStarboard = "motor_desires.starboard"
SurgePort = "motor_desires.aft_starboard"
SurgeStarboard = "motor_desires.sway_fore"
RampDec = "ramp.ramp_dec"
RampInc = "ramp.ramp_inc"
RampPeriod = "ramp.ramp_period"
BatteryVoltage = "minipower_status.vout"
SurgeStarboardRamp = "ramp_status.starboard_ramp"
SurgePortRamp = "ramp_status.port_ramp"
SwayPortRamp = "ramp_status.sway_fore_ramp"
SwayStarboardRamp = "ramp_status.sway_aft_ramp"
DepthForeRamp = "ramp_status.fore_port_ramp"
DepthAftRamp = "ramp_status.aft_starboard_ramp"
