[devices.thrusters.vars]
Thruster1PwmVal = "motor_desires.aft_port"
Thruster4PwmVal = "motor_desires.sway_aft"
Thruster5PwmVal = "motor_desires.sway_fore"
Thruster6PwmVal = "motor_desires.aft_starboard"

Thruster1PwmReadBack = "ramp_status.aft_port_ramp"
Thruster4PwmReadBack = "ramp_status.sway_aft_ramp"
Thruster5PwmReadBack = "ramp_status.sway_fore_ramp"
Thruster6PwmReadBack = "ramp_status.aft_starboard_ramp"

RampPeriod = "ramp.ramp_period"
RampInc = "ramp.ramp_inc"
RampDec = "ramp.ramp_dec"
