[devices.thrusters2.vars]
Thruster1PwmVal = "motor_desires.fore_starboard"
Thruster4PwmVal = "motor_desires.fore_port"
Thruster5PwmVal = "motor_desires.port"
Thruster6PwmVal = "motor_desires.starboard"

Thruster1PwmReadback = "ramp_status.fore_starboard_ramp"
Thruster4PwmReadback = "ramp_status.fore_port_ramp"
Thruster5PwmReadback = "ramp_status.port_ramp"
Thruster6PwmReadback = "ramp_status.starboard_ramp"

RampPeriod = "ramp.ramp_period"
RampInc = "ramp.ramp_inc"
RampDec = "ramp.ramp_dec"

