[devices.thrusters.vars]
Thruster2PwmVal = "motor_desires.aft_starboard"
Thruster4PwmVal = "motor_desires.fore_starboard"
Thruster5PwmVal = "motor_desires.starboard"
Thruster6PwmVal = "motor_desires.sway_aft"

Thruster2PwmReadBack = "ramp_status.fore_port_ramp"
Thruster4PwmReadBack = "ramp_status.sway_fore_ramp"
Thruster5PwmReadBack = "ramp_status.port_ramp"
Thruster6PwmReadBack = "ramp_status.aft_port_ramp"

RampPeriod = "ramp.ramp_period"
RampInc = "ramp.ramp_inc"
RampDec = "ramp.ramp_dec"
