#!/usr/bin/env bash

PORT=8000
[ -n "$1" ]; PORT=$1

# http://stackoverflow.com/a/2173421
trap 'trap - SIGTERM && kill -- -$$' SIGINT SIGTERM EXIT
python3 -m http.server --cgi $PORT &
cat << END | entr ./build
peacock.pdc
style.css
END
